[2024-03-14 01:28:42,498] [INFO] [server_logger.py:29] Logger initialized
[2024-03-14 01:28:42,522] [INFO] [login.py:17] Connection Successful
[2024-03-14 01:28:42,524] [INFO] [register.py:17] Connection Successful
[2024-03-14 01:28:42,527] [INFO] [survey.py:15] Connection Successful
[2024-03-14 01:28:42,529] [INFO] [query.py:13] Connection Successful
[2024-03-14 01:28:51,105] [WARNING] [login.py:45] Invalid login attempt with email: iad@dsf.add
[2024-03-14 01:28:53,149] [WARNING] [login.py:42] Invalid login attempt for email: ss@ss.ss
[2024-03-14 01:28:57,240] [INFO] [login.py:33] Successful login for user: ss@ss.ss
[2024-03-14 01:28:59,295] [ERROR] [query.py:26] Error in user_query_model: 1054 (42S22): Unknown column 'user_id' in 'field list'
[2024-03-14 01:28:59,297] [INFO] [general_controller.py:14] User query received successfully
[2024-03-14 01:29:01,384] [INFO] [register_controller.py:14] User registration successful
[2024-03-14 01:29:03,419] [INFO] [register.py:34] Added user with ID 6
[2024-03-14 01:29:03,420] [INFO] [register_controller.py:14] User registration successful
[2024-03-14 01:29:05,449] [INFO] [register_controller.py:27] User registration successful
[2024-03-14 01:29:07,485] [INFO] [register.py:55] Added user with ID 62
[2024-03-14 01:29:07,486] [INFO] [register_controller.py:27] User registration successful
